const product = [
  {
    _id: "1",
    name: "Airdopes 121v2 TWS Earbuds",
    image: "./images/earbuds.jpg",
    description: "Brand new Earbuds with noice reduction and game mode",
    brand: "Xiomi",
    category: "Electronics",
    price: 10.19,
    countInStock: 10,
    rating: 4.0,
    numReviews: 10,
  },
  {
    _id: "2",
    name: "Tab Micomax 32GB",
    image: "./images/tab.jpg",
    description: "Brand new Sumsung Tab with Quad Core Processor",
    brand: "Sumsung",
    category: "Electronics",
    price: 30.19,
    countInStock: 10,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: "3",
    name: "Watch Apple Series 6",
    image: "./images/watch.jpeg",
    description:
      "Brand new Apple watch with Heartbeat Sensor and AMOLED display",
    brand: "Apple",
    category: "Electronics",
    price: 20.19,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },

  {
    _id: "4",
    name: "Airdopes 121v2 TWS Earbuds",
    image: "./images/earbuds.jpg",
    description: "Brand new Earbuds with noice reduction and game mode",
    brand: "Xiomi",
    category: "Electronics",
    price: 10.19,
    countInStock: 10,
    rating: 4.0,
    numReviews: 10,
  },
  {
    _id: "5",
    name: "Tab Micomax 32GB",
    image: "./images/tab.jpg",
    description: "Brand new Sumsung Tab with Quad Core Processor",
    brand: "Sumsung",
    category: "Electronics",
    price: 30.19,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "6",
    name: "Watch Apple Series 6",
    image: "./images/watch.jpeg",
    description:
      "Brand new Apple watch with Heartbeat Sensor and AMOLED display",
    brand: "Apple",
    category: "Electronics",
    price: 20.19,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
];

export default product;
